jobs: 
- job: myjob 
  displayName: MyJob 
  pool: 
    name: 'Default' 
  steps: 
  - task: oc-cmd@2 
    inputs: 
      openshiftService: 'My Openshift' 
      version: '4.1' 
      cmd: 'oc new-app https://github.com/lstocchi/nodejs-ex -l name=demoapp' 
      uselocalOc: true